name: CI - Build and Deploy
run-name: Deploy by ${{ github.actor }} 🚀
on:
  push:
    branches:
      - main

jobs:
  :
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd backend
          npm install
          cd frontend
          npm install
      - name: run backend
        run: |
          cd backend
          npm run dev
      - name: run fronted
        run: |
          cd frontend
          npm run build