name: CI - Build and Deploy
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd back-end
          npm install
          
          cd ../front-end
          npm install

      - name: Run back-end
        env:
          $DB_HOST: mongodb://localhost:27017
        run: |
          cd back-end
          npm run dev &
          sleep 10
          pkill -f "npm run dev"
          npm run test

      - name: Run front-end
        run: |
          cd front-end
          npm run dev &
          sleep 10
          pkill -f "npm run dev"
