name: CI - Build and Deploy
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DB_HOST: "mongodb+srv://arthurmelo1918:71JuBrKKWQr6kAfU@dubium0.o4ru6rq.mongodb.net/Dubium"
      API_KEY: "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"
      ORG: "org-ZKypXgICyNRD0O6urMB1v5Eh"

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd back-end
          npm install
          
          cd ../front-end
          npm install

      - name: Run back-end
        run: |
          cd back-end
          npm run test
          npm run dev &
          sleep 10
          pkill -f "npm run dev"

      - name: Run front-end
        run: |
          cd front-end
          npm run dev &
          sleep 10
          pkill -f "npm run dev"
