name: CI - Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd backend
          npm install
          
          cd ../frontend
          npm install

      - name: Run backend
        run: |
          cd backend
          npm run dev

      - name: Run frontend
        run: |
          cd frontend
          npm run build
